PRAGMA foreign_keys = ON;

CREATE TABLE Vehicle (id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE ConsumptionProfile (id TEXT PRIMARY KEY, vehicleID TEXT NOT NULL REFERENCES Vehicle(id), consumptionPer100 REAL NOT NULL CHECK (consumptionPer100 > 0));
CREATE TABLE FuelPrice (id TEXT PRIMARY KEY, vehicleID TEXT NOT NULL REFERENCES Vehicle(id), unitPriceMilliEUR INTEGER NOT NULL CHECK (unitPriceMilliEUR > 0), occurredAt TEXT NOT NULL);
CREATE TABLE Person (id TEXT PRIMARY KEY, name TEXT NOT NULL, isOwner INTEGER NOT NULL DEFAULT 0 CHECK (isOwner IN (0,1)));
CREATE UNIQUE INDEX one_owner ON Person(isOwner) WHERE isOwner = 1;
CREATE TABLE "Group" (id TEXT PRIMARY KEY, name TEXT NOT NULL);
CREATE TABLE GroupMember (groupID TEXT NOT NULL REFERENCES "Group"(id), personID TEXT NOT NULL REFERENCES Person(id), PRIMARY KEY(groupID, personID));
CREATE TABLE Trip (id TEXT PRIMARY KEY, vehicleID TEXT NOT NULL REFERENCES Vehicle(id), startedAt TEXT NOT NULL, endedAt TEXT, status TEXT NOT NULL CHECK(status IN ('planned','active','interrupted','completed')), consumptionProfileID TEXT REFERENCES ConsumptionProfile(id), CHECK(endedAt IS NULL OR endedAt >= startedAt));
CREATE UNIQUE INDEX one_active_trip ON Trip((1)) WHERE status IN ('active','interrupted');
CREATE INDEX trip_started_at ON Trip(startedAt);
CREATE INDEX trip_status ON Trip(status);
CREATE TABLE TripParticipant (tripID TEXT NOT NULL REFERENCES Trip(id) ON DELETE CASCADE, personID TEXT NOT NULL REFERENCES Person(id), role TEXT NOT NULL, sortOrder INTEGER NOT NULL, PRIMARY KEY(tripID, personID));
CREATE TABLE ManualExpense (id TEXT PRIMARY KEY, tripID TEXT NOT NULL REFERENCES Trip(id) ON DELETE CASCADE, amountCents INTEGER NOT NULL CHECK(amountCents > 0));
CREATE TABLE PaymentBatch (id TEXT PRIMARY KEY, personID TEXT NOT NULL REFERENCES Person(id), occurredAt TEXT NOT NULL);
CREATE TABLE LedgerEntry (id TEXT PRIMARY KEY, kind TEXT NOT NULL CHECK(kind IN ('charge','payment')), debtorID TEXT NOT NULL REFERENCES Person(id), creditorID TEXT NOT NULL REFERENCES Person(id), amountCents INTEGER NOT NULL CHECK(amountCents > 0), groupID TEXT NOT NULL REFERENCES "Group"(id), tripID TEXT REFERENCES Trip(id) ON DELETE CASCADE, paymentBatchID TEXT REFERENCES PaymentBatch(id) ON DELETE CASCADE, occurredAt TEXT NOT NULL, CHECK(debtorID <> creditorID), CHECK((kind = 'charge' AND tripID IS NOT NULL AND paymentBatchID IS NULL) OR (kind = 'payment' AND paymentBatchID IS NOT NULL AND tripID IS NULL)));
CREATE UNIQUE INDEX one_charge_per_person_trip ON LedgerEntry(debtorID, tripID) WHERE kind = 'charge';
CREATE INDEX ledger_person_group_date ON LedgerEntry(debtorID, groupID, occurredAt);
CREATE INDEX ledger_trip ON LedgerEntry(tripID);
CREATE TABLE ActiveTripState (tripID TEXT PRIMARY KEY REFERENCES Trip(id) ON DELETE CASCADE, sequence INTEGER NOT NULL, savedAt TEXT NOT NULL, state TEXT NOT NULL);
